- name: conditions testing
  hosts: local
  connection: local
  vars_prompt:
    prompt: enter the number
    private: false

  tasks:
  - name: print number 
    ansible.builtin.debug:
      msg: "print number {{Number}}"
    when: Number < 100