- name: conditions testing
  hosts: local
  connection: local
  vars_prompt:
  - name: NUMBER
    prompt: enter the number
    private: false

  tasks:
  - name: print the number 
    ansible.builtin.debug:
      msg: "print number {{NUMBER}}"
   