- name: functions in ansible
  hosts: local
  connection: local
  tasks:
  - name: convert to uppercase
    vars:
      name: "naveen kumar c"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"
