- name: variables from arguments
  hosts: local
  connection: local
 
  tasks:
  - name: print about course info
    ansible.builtin.debug:
      msg: "hii  iam {{TRAINER}} who giving course {{COURSE}} with {{TIME}}"
