- name: variable with task
  hosts: local
  connection: local
  vars: 
    COURSE: Devops
    TRAINER: Naveen
    TIME: 50hr
  tasks:
    - name: print course info 
      vars: 
        COURSE: Ansible
      ansible.builtin.debug:
        msg: "Iam {{TRAINER}} ,and giving course {{COURSE}}, with {{TIME}}"

- name: print about course again
  ansible.builtin.debug:
     msg: "iam {{TRAINER}} who giving course {{COURSE}} with {{TIME}}"